class ElementAkinator:
    def __init__(self):
        self.elements = {
            "Hydrogen": {"type": "non-metal", "group": "1", "period": "1", "state": "gas", "atomic_number": "1",
                         "electron_config": "1s¹", "charge": "+1", "metallic": "non-metal", "melting_point": "-259",
                         "density": "0.00008988", "valence_electrons": "1", "radioactive": "no"},
            "Helium": {"type": "noble gas", "group": "18", "period": "1", "state": "gas", "atomic_number": "2",
                       "electron_config": "1s²", "charge": "0", "metallic": "non-metal", "melting_point": "-272",
                       "density": "0.0001785", "valence_electrons": "0", "radioactive": "no"},
            "Lithium": {"type": "alkali metal", "group": "1", "period": "2", "state": "solid", "atomic_number": "3",
                        "electron_config": "[He] 2s¹", "charge": "+1", "metallic": "metal", "melting_point": "180",
                        "density": "0.534", "valence_electrons": "1", "radioactive": "no"},
            "Beryllium": {"type": "alkaline earth metal", "group": "2", "period": "2", "state": "solid",
                          "atomic_number": "4", "electron_config": "[He] 2s²", "charge": "+2", "metallic": "metal",
                          "melting_point": "1287", "density": "1.85", "valence_electrons": "2", "radioactive": "no"},
            "Boron": {"type": "metalloid", "group": "13", "period": "2", "state": "solid", "atomic_number": "5",
                      "electron_config": "[He] 2s² 2p¹", "charge": "+3", "metallic": "non-metal", "melting_point": "2075",
                      "density": "2.34", "valence_electrons": "3", "radioactive": "no"},
            "Carbon": {"type": "non-metal", "group": "14", "period": "2", "state": "solid", "atomic_number": "6",
                       "electron_config": "[He] 2s² 2p²", "charge": "-4, +2, +4", "metallic": "non-metal",
                       "melting_point": "3550", "density": "2.267", "valence_electrons": "4", "radioactive": "no"},
            "Nitrogen": {"type": "non-metal", "group": "15", "period": "2", "state": "gas", "atomic_number": "7",
                         "electron_config": "[He] 2s² 2p³", "charge": "-3", "metallic": "non-metal", "melting_point": "-210",
                         "density": "0.001251", "valence_electrons": "5", "radioactive": "no"},
            "Oxygen": {"type": "non-metal", "group": "16", "period": "2", "state": "gas", "atomic_number": "8",
                       "electron_config": "[He] 2s² 2p⁴", "charge": "-2", "metallic": "non-metal", "melting_point": "-218",
                       "density": "0.001429", "valence_electrons": "6", "radioactive": "no"},
            "Fluorine": {"type": "non-metal", "group": "17", "period": "2", "state": "gas", "atomic_number": "9",
                         "electron_config": "[He] 2s² 2p⁵", "charge": "-1", "metallic": "non-metal", "melting_point": "-220",
                         "density": "0.001696", "valence_electrons": "7", "radioactive": "no"},
            "Neon": {"type": "noble gas", "group": "18", "period": "2", "state": "gas", "atomic_number": "10",
                     "electron_config": "[He] 2s² 2p⁶", "charge": "0", "metallic": "non-metal", "melting_point": "-249",
                     "density": "0.0008999", "valence_electrons": "8", "radioactive": "no"},
            "Sodium": {"type": "alkali metal", "group": "1", "period": "3", "state": "solid", "atomic_number": "11",
                       "electron_config": "[Ne] 3s¹", "charge": "+1", "metallic": "metal", "melting_point": "98",
                       "density": "0.968", "valence_electrons": "1", "radioactive": "no"},
            "Magnesium": {"type": "alkaline earth metal", "group": "2", "period": "3", "state": "solid",
                          "atomic_number": "12", "electron_config": "[Ne] 3s²", "charge": "+2", "metallic": "metal",
                          "melting_point": "650", "density": "1.738", "valence_electrons": "2", "radioactive": "no"},
            "Aluminum": {"type": "metal", "group": "13", "period": "3", "state": "solid", "atomic_number": "13",
                         "electron_config": "[Ne] 3s² 3p¹", "charge": "+3", "metallic": "metal", "melting_point": "660",
                         "density": "2.6989", "valence_electrons": "3", "radioactive": "no"},
            "Silicon": {"type": "metalloid", "group": "14", "period": "3", "state": "solid", "atomic_number": "14",
                        "electron_config": "[Ne] 3s² 3p²", "charge": "+4", "metallic": "non-metal", "melting_point": "1414",
                        "density": "2.3296", "valence_electrons": "4", "radioactive": "no"},
            "Phosphorus": {"type": "non-metal", "group": "15", "period": "3", "state": "solid", "atomic_number": "15",
                           "electron_config": "[Ne] 3s² 3p³", "charge": "-3", "metallic": "non-metal", "melting_point": "44",
                           "density": "1.82", "valence_electrons": "5", "radioactive": "no"},
            "Sulfur": {"type": "non-metal", "group": "16", "period": "3", "state": "solid", "atomic_number": "16",
                       "electron_config": "[Ne] 3s² 3p⁴", "charge": "-2", "metallic": "non-metal", "melting_point": "115",
                       "density": "2.067", "valence_electrons": "6", "radioactive": "no"},
            "Chlorine": {"type": "non-metal", "group": "17", "period": "3", "state": "gas", "atomic_number": "17",
                         "electron_config": "[Ne] 3s² 3p⁵", "charge": "-1", "metallic": "non-metal", "melting_point": "-101",
                         "density": "0.003214", "valence_electrons": "7", "radioactive": "no"},
            "Argon": {"type": "noble gas", "group": "18", "period": "3", "state": "gas", "atomic_number": "18",
                      "electron_config": "[Ne] 3s² 3p⁶", "charge": "0", "metallic": "non-metal", "melting_point": "-189",
                      "density": "0.0017837", "valence_electrons": "8", "radioactive": "no"},
            "Potassium": {"type": "alkali metal", "group": "1", "period": "4", "state": "solid", "atomic_number": "19",
                          "electron_config": "[Ar] 4s¹", "charge": "+1", "metallic": "metal", "melting_point": "64",
                          "density": "0.862", "valence_electrons": "1", "radioactive": "no"},
            "Calcium": {"type": "alkaline earth metal", "group": "2", "period": "4", "state": "solid", "atomic_number": "20",
                        "electron_config": "[Ar] 4s²", "charge": "+2", "metallic": "metal", "melting_point": "839",
                        "density": "1.54", "valence_electrons": "2", "radioactive": "no"},
            "Scandium": {"type": "metal", "group": "3", "period": "4", "state": "solid", "atomic_number": "21",
                         "electron_config": "[Ar] 3d¹ 4s²", "charge": "+3", "metallic": "metal", "melting_point": "1541",
                         "density": "2.989", "valence_electrons": "3", "radioactive": "no"},
            "Titanium": {"type": "metal", "group": "4", "period": "4", "state": "solid", "atomic_number": "22",
                         "electron_config": "[Ar] 3d² 4s²", "charge": "+4", "metallic": "metal", "melting_point": "1668",
                         "density": "4.506", "valence_electrons": "4", "radioactive": "no"},
            "Vanadium": {"type": "metal", "group": "5", "period": "4", "state": "solid", "atomic_number": "23",
                         "electron_config": "[Ar] 3d³ 4s²", "charge": "+5", "metallic": "metal", "melting_point": "1910",
                         "density": "6.11", "valence_electrons": "5", "radioactive": "no"},
            "Chromium": {"type": "metal", "group": "6", "period": "4", "state": "solid", "atomic_number": "24",
                         "electron_config": "[Ar] 3d⁵ 4s¹", "charge": "+2, +3, +6", "metallic": "metal",
                         "melting_point": "1907", "density": "7.14", "valence_electrons": "6", "radioactive": "no"},
            "Manganese": {"type": "metal", "group": "7", "period": "4", "state": "solid", "atomic_number": "25",
                          "electron_config": "[Ar] 3d⁵ 4s²", "charge": "+2, +4, +7", "metallic": "metal",
                          "melting_point": "1246", "density": "7.44", "valence_electrons": "7", "radioactive": "no"},
            "Iron": {"type": "metal", "group": "8", "period": "4", "state": "solid", "atomic_number": "26",
                     "electron_config": "[Ar] 3d⁶ 4s²", "charge": "+2, +3", "metallic": "metal", "melting_point": "1538",
                     "density": "7.874", "valence_electrons": "8", "radioactive": "no"},
            "Cobalt": {"type": "metal", "group": "9", "period": "4", "state": "solid", "atomic_number": "27",
                       "electron_config": "[Ar] 3d⁷ 4s²", "charge": "+2, +3", "metallic": "metal", "melting_point": "1495",
                       "density": "8.86", "valence_electrons": "9", "radioactive": "no"},
            "Nickel": {"type": "metal", "group": "10", "period": "4", "state": "solid", "atomic_number": "28",
                       "electron_config": "[Ar] 3d⁸ 4s²", "charge": "+2, +3", "metallic": "metal", "melting_point": "1453",
                       "density": "8.912", "valence_electrons": "10", "radioactive": "no"},
            "Copper": {"type": "metal", "group": "11", "period": "4", "state": "solid", "atomic_number": "29",
                       "electron_config": "[Ar] 3d¹⁰ 4s¹", "charge": "+1, +2", "metallic": "metal", "melting_point": "1085",
                       "density": "8.96", "valence_electrons": "11", "radioactive": "no"},
            "Zinc": {"type": "metal", "group": "12", "period": "4", "state": "solid", "atomic_number": "30",
                     "electron_config": "[Ar] 3d¹⁰ 4s²", "charge": "+2", "metallic": "metal", "melting_point": "419",
                     "density": "7.134", "valence_electrons": "12", "radioactive": "no"},
            "Gallium": {"type": "metal", "group": "13", "period": "4", "state": "solid", "atomic_number": "31",
                        "electron_config": "[Ar] 3d¹⁰ 4s² 4p¹", "charge": "+3", "metallic": "metal", "melting_point": "30",
                        "density": "5.907", "valence_electrons": "13", "radioactive": "no"},
            "Germanium": {"type": "metalloid", "group": "14", "period": "4", "state": "solid", "atomic_number": "32",
                          "electron_config": "[Ar] 3d¹⁰ 4s² 4p²", "charge": "+4", "metallic": "non-metal",
                          "melting_point": "938", "density": "5.323", "valence_electrons": "14", "radioactive": "no"},
            "Arsenic": {"type": "metalloid", "group": "15", "period": "4", "state": "solid", "atomic_number": "33",
                        "electron_config": "[Ar] 3d¹⁰ 4s² 4p³", "charge": "-3, +3, +5", "metallic": "non-metal",
                        "melting_point": "814", "density": "5.776", "valence_electrons": "15", "radioactive": "no"},
            "Selenium": {"type": "non-metal", "group": "16", "period": "4", "state": "solid", "atomic_number": "34",
                         "electron_config": "[Ar] 3d¹⁰ 4s² 4p⁴", "charge": "-2", "metallic": "non-metal",
                         "melting_point": "221", "density": "4.809", "valence_electrons": "16", "radioactive": "no"},
            "Bromine": {"type": "non-metal", "group": "17", "period": "4", "state": "liquid", "atomic_number": "35",
                        "electron_config": "[Ar] 3d¹⁰ 4s² 4p⁵", "charge": "-1", "metallic": "non-metal",
                        "melting_point": "-7", "density": "3.122", "valence_electrons": "17", "radioactive": "no"},
            "Krypton": {"type": "noble gas", "group": "18", "period": "4", "state": "gas", "atomic_number": "36",
                        "electron_config": "[Ar] 3d¹⁰ 4s² 4p⁶", "charge": "0", "metallic": "non-metal",
                        "melting_point": "-157", "density": "0.003733", "valence_electrons": "18", "radioactive": "no"},
            "Rubidium": {"type": "alkali metal", "group": "1", "period": "5", "state": "solid", "atomic_number": "37",
                         "electron_config": "[Kr] 5s¹", "charge": "+1", "metallic": "metal", "melting_point": "39",
                         "density": "1.532", "valence_electrons": "1", "radioactive": "no"},
            "Strontium": {"type": "alkaline earth metal", "group": "2", "period": "5", "state": "solid",
                          "atomic_number": "38", "electron_config": "[Kr] 5s²", "charge": "+2", "metallic": "metal",
                          "melting_point": "769", "density": "2.64", "valence_electrons": "2", "radioactive": "no"},
            "Yttrium": {"type": "metal", "group": "3", "period": "5", "state": "solid", "atomic_number": "39",
                        "electron_config": "[Kr] 4d¹ 5s²", "charge": "+3", "metallic": "metal", "melting_point": "1522",
                        "density": "4.469", "valence_electrons": "3", "radioactive": "no"},
            "Zirconium": {"type": "metal", "group": "4", "period": "5", "state": "solid", "atomic_number": "40",
                          "electron_config": "[Kr] 4d² 5s²", "charge": "+4", "metallic": "metal", "melting_point": "1852",
                          "density": "6.506", "valence_electrons": "4", "radioactive": "no"},
            "Niobium": {"type": "metal", "group": "5", "period": "5", "state": "solid", "atomic_number": "41",
                        "electron_config": "[Kr] 4d⁴ 5s¹", "charge": "+5", "metallic": "metal", "melting_point": "2477",
                        "density": "8.57", "valence_electrons": "5", "radioactive": "no"},
            "Molybdenum": {"type": "metal", "group": "6", "period": "5", "state": "solid", "atomic_number": "42",
                           "electron_config": "[Kr] 4d⁵ 5s¹", "charge": "+6", "metallic": "metal", "melting_point": "2623",
                           "density": "10.28", "valence_electrons": "6", "radioactive": "no"},
            "Technetium": {"type": "metal", "group": "7", "period": "5", "state": "solid", "atomic_number": "43",
                           "electron_config": "[Kr] 4d⁵ 5s²", "charge": "+4, +7", "metallic": "metal",
                           "melting_point": "2157", "density": "11.49", "valence_electrons": "7", "radioactive": "yes"},
            "Ruthenium": {"type": "metal", "group": "8", "period": "5", "state": "solid", "atomic_number": "44",
                          "electron_config": "[Kr] 4d⁷ 5s¹", "charge": "+3, +4, +8", "metallic": "metal",
                          "melting_point": "2334", "density": "12.37", "valence_electrons": "8", "radioactive": "no"},
            "Rhodium": {"type": "metal", "group": "9", "period": "5", "state": "solid", "atomic_number": "45",
                        "electron_config": "[Kr] 4d⁸ 5s¹", "charge": "+2, +3", "metallic": "metal", "melting_point": "1964",
                        "density": "12.41", "valence_electrons": "9", "radioactive": "no"},
            "Palladium": {"type": "metal", "group": "10", "period": "5", "state": "solid", "atomic_number": "46",
                           "electron_config": "[Kr] 4d¹⁰", "charge": "+2, +4", "metallic": "metal", "melting_point": "1555",
                           "density": "12.023", "valence_electrons": "10", "radioactive": "no"},
            "Silver": {"type": "metal", "group": "11", "period": "5", "state": "solid", "atomic_number": "47",
                       "electron_config": "[Kr] 4d¹⁰ 5s¹", "charge": "+1", "metallic": "metal", "melting_point": "962",
                       "density": "10.49", "valence_electrons": "11", "radioactive": "no"},
            "Cadmium": {"type": "metal", "group": "12", "period": "5", "state": "solid", "atomic_number": "48",
                        "electron_config": "[Kr] 4d¹⁰ 5s²", "charge": "+2", "metallic": "metal", "melting_point": "321",
                        "density": "8.65", "valence_electrons": "12", "radioactive": "no"},
            "Indium": {"type": "metal", "group": "13", "period": "5", "state": "solid", "atomic_number": "49",
                       "electron_config": "[Kr] 4d¹⁰ 5s² 5p¹", "charge": "+3", "metallic": "metal", "melting_point": "157",
                       "density": "7.31", "valence_electrons": "13", "radioactive": "no"},
            "Tin": {"type": "metal", "group": "14", "period": "5", "state": "solid", "atomic_number": "50",
                     "electron_config": "[Kr] 4d¹⁰ 5s² 5p²", "charge": "+2, +4", "metallic": "metal", "melting_point": "232",
                     "density": "7.365", "valence_electrons": "14", "radioactive": "no"},
            "Antimony": {"type": "metalloid", "group": "15", "period": "5", "state": "solid", "atomic_number": "51",
                         "electron_config": "[Kr] 4d¹⁰ 5s² 5p³", "charge": "-3, +3, +5", "metallic": "non-metal",
                         "melting_point": "631", "density": "6.697", "valence_electrons": "15", "radioactive": "no"},
            "Tellurium": {"type": "metalloid", "group": "16", "period": "5", "state": "solid", "atomic_number": "52",
                           "electron_config": "[Kr] 4d¹⁰ 5s² 5p⁴", "charge": "-2, +4, +6", "metallic": "non-metal",
                           "melting_point": "449", "density": "6.24", "valence_electrons": "16", "radioactive": "no"},
            "Iodine": {"type": "non-metal", "group": "17", "period": "5", "state": "solid", "atomic_number": "53",
                       "electron_config": "[Kr] 4d¹⁰ 5s² 5p⁵", "charge": "-1", "metallic": "non-metal",
                       "melting_point": "114", "density": "4.933", "valence_electrons": "17", "radioactive": "no"},
            "Xenon": {"type": "noble gas", "group": "18", "period": "5", "state": "gas", "atomic_number": "54",
                      "electron_config": "[Kr] 4d¹⁰ 5s² 5p⁶", "charge": "0", "metallic": "non-metal",
                      "melting_point": "-112", "density": "0.005887", "valence_electrons": "18", "radioactive": "no"},
            "Cesium": {"type": "alkali metal", "group": "1", "period": "6", "state": "solid", "atomic_number": "55",
                       "electron_config": "[Xe] 6s¹", "charge": "+1", "metallic": "metal", "melting_point": "29",
                       "density": "1.873", "valence_electrons": "1", "radioactive": "no"},
            "Barium": {"type": "alkaline earth metal", "group": "2", "period": "6", "state": "solid",
                       "atomic_number": "56", "electron_config": "[Xe] 6s²", "charge": "+2", "metallic": "metal",
                       "melting_point": "725", "density": "3.594", "valence_electrons": "2", "radioactive": "no"},
            "Lanthanum": {"type": "metal", "group": "", "period": "6", "state": "solid", "atomic_number": "57",
                          "electron_config": "[Xe] 5d¹ 6s²", "charge": "+3", "metallic": "metal", "melting_point": "921",
                          "density": "6.145", "valence_electrons": "3", "radioactive": "no"},
            "Cerium": {"type": "metal", "group": "", "period": "6", "state": "solid", "atomic_number": "58",
                        "electron_config": "[Xe] 4f¹ 5d¹ 6s²", "charge": "+3, +4", "metallic": "metal",
                        "melting_point": "798", "density": "6.77", "valence_electrons": "4", "radioactive": "no"},
            "Praseodymium": {"type": "metal", "group": "", "period": "6", "state": "solid", "atomic_number": "59",
                             "electron_config": "[Xe] 4f³ 6s²", "charge": "+3", "metallic": "metal",
                             "melting_point": "931", "density": "6.773", "valence_electrons": "5", "radioactive": "no"},
            "Neodymium": {"type": "metal", "group": "", "period": "6", "state": "solid", "atomic_number": "60",
                          "electron_config": "[Xe] 4f⁴ 6s²", "charge": "+3", "metallic": "metal", "melting_point": "1024",
                          "density": "7.007", "valence_electrons": "6", "radioactive": "no"},
            "Promethium": {"type": "metal", "group": "", "period": "6", "state": "solid", "atomic_number": "61",
                            "electron_config": "[Xe] 4f⁵ 6s²", "charge": "+3", "metallic": "metal",
                            "melting_point": "1042", "density": "7.26", "valence_electrons": "7", "radioactive": "yes"},
            "Samarium": {"type": "metal", "group": "", "period": "6", "state": "solid", "atomic_number": "62",
                          "electron_config": "[Xe] 4f⁶ 6s²", "charge": "+3", "metallic": "metal", "melting_point": "1072",
                          "density": "7.52", "valence_electrons": "8", "radioactive": "no"},
            "Europium": {"type": "metal", "group": "", "period": "6", "state": "solid", "atomic_number": "63",
                         "electron_config": "[Xe] 4f⁷ 6s²", "charge": "+2, +3", "metallic": "metal",
                         "melting_point": "822", "density": "5.243", "valence_electrons": "9", "radioactive": "no"},
            "Gadolinium": {"type": "metal", "group": "", "period": "6", "state": "solid", "atomic_number": "64",
                           "electron_config": "[Xe] 4f⁷ 5d¹ 6s²", "charge": "+3", "metallic": "metal",
                           "melting_point": "1311", "density": "7.895", "valence_electrons": "10", "radioactive": "no"},
            "Terbium": {"type": "metal", "group": "", "period": "6", "state": "solid", "atomic_number": "65",
                        "electron_config": "[Xe] 4f⁹ 6s²", "charge": "+3", "metallic": "metal", "melting_point": "1360",
                        "density": "8.229", "valence_electrons": "11", "radioactive": "no"},
            "Thulium": {
    "type": "metal",
    "group": "",
    "period": "6",
    "state": "solid",
    "atomic_number": "69",
    "electron_config": "[Xe] 4f¹³ 6s²",
    "charge": "+3",
    "metallic": "metal",
    "melting_point": "1545",
    "density": "9.321",
    "valence_electrons": "15",
    "radioactive": "no"
},
"Ytterbium": {
    "type": "metal",
    "group": "",
    "period": "6",
    "state": "solid",
    "atomic_number": "70",
    "electron_config": "[Xe] 4f¹⁴ 6s²",
    "charge": "+3",
    "metallic": "metal",
    "melting_point": "1097",
    "density": "6.965",
    "valence_electrons": "16",
    "radioactive": "no"
},
"Lutetium": {
    "type": "metal",
    "group": "",
    "period": "6",
    "state": "solid",
    "atomic_number": "71",
    "electron_config": "[Xe] 4f¹⁴ 5d¹ 6s²",
    "charge": "+3",
    "metallic": "metal",
    "melting_point": "1663",
    "density": "9.841",
    "valence_electrons": "17",
    "radioactive": "no"
},
"Hafnium": {
    "type": "metal",
    "group": "4",
    "period": "6",
    "state": "solid",
    "atomic_number": "72",
    "electron_config": "[Xe] 4f¹⁴ 5d² 6s²",
    "charge": "+4",
    "metallic": "metal",
    "melting_point": "2233",
    "density": "13.31",
    "valence_electrons": "18",
    "radioactive": "no"
},
"Tantalum": {
    "type": "metal",
    "group": "5",
    "period": "6",
    "state": "solid",
    "atomic_number": "73",
    "electron_config": "[Xe] 4f¹⁴ 5d³ 6s²",
    "charge": "+5",
    "metallic": "metal",
    "melting_point": "3017",
    "density": "16.654",
    "valence_electrons": "18",
    "radioactive": "no"
},
"Tungsten": {
    "type": "metal",
    "group": "6",
    "period": "6",
    "state": "solid",
    "atomic_number": "74",
    "electron_config": "[Xe] 4f¹⁴ 5d⁴ 6s²",
    "charge": "+6",
    "metallic": "metal",
    "melting_point": "3422",
    "density": "19.25",
    "valence_electrons": "18",
    "radioactive": "no"
},
"Rhenium": {
    "type": "metal",
    "group": "7",
    "period": "6",
    "state": "solid",
    "atomic_number": "75",
    "electron_config": "[Xe] 4f¹⁴ 5d⁵ 6s²",
    "charge": "+7",
    "metallic": "metal",
    "melting_point": "3186",
    "density": "21.02",
    "valence_electrons": "18",
    "radioactive": "no"
},
"Osmium": {
    "type": "metal",
    "group": "8",
    "period": "6",
    "state": "solid",
    "atomic_number": "76",
    "electron_config": "[Xe] 4f¹⁴ 5d⁶ 6s²",
    "charge": "+4, +6, +8",
    "metallic": "metal",
    "melting_point": "3033",
    "density": "22.59",
    "valence_electrons": "18",
    "radioactive": "no"
},
"Iridium": {
    "type": "metal",
    "group": "9",
    "period": "6",
    "state": "solid",
    "atomic_number": "77",
    "electron_config": "[Xe] 4f¹⁴ 5d⁷ 6s²",
    "charge": "+3, +4",
    "metallic": "metal",
    "melting_point": "2446",
    "density": "22.56",
    "valence_electrons": "18",
    "radioactive": "no"
},
"Platinum": {
    "type": "metal",
    "group": "10",
    "period": "6",
    "state": "solid",
    "atomic_number": "78",
    "electron_config": "[Xe] 4f¹⁴ 5d⁹ 6s¹",
    "charge": "+2, +4",
    "metallic": "metal",
    "melting_point": "1768",
    "density": "21.45",
    "valence_electrons": "18",
    "radioactive": "no"
},
"Gold": {
    "type": "metal",
    "group": "11",
    "period": "6",
    "state": "solid",
    "atomic_number": "79",
    "electron_config": "[Xe] 4f¹⁴ 5d¹⁰ 6s¹",
    "charge": "+1, +3",
    "metallic": "metal",
    "melting_point": "1064",
    "density": "19.32",
    "valence_electrons": "18",
    "radioactive": "no"
},
"Mercury": {
    "type": "metal",
    "group": "12",
    "period": "6",
    "state": "liquid",
    "atomic_number": "80",
    "electron_config": "[Xe] 4f¹⁴ 5d¹⁰ 6s²",
    "charge": "+1, +2",
    "metallic": "metal",
    "melting_point": "-39",
    "density": "13.5336",
    "valence_electrons": "18",
    "radioactive": "no"
},
"Thallium": {
    "type": "metal",
    "group": "13",
    "period": "6",
    "state": "solid",
    "atomic_number": "81",
    "electron_config": "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹",
    "charge": "+1, +3",
    "metallic": "metal",
    "melting_point": "303",
    "density": "11.85",
    "valence_electrons": "18",
    "radioactive": "yes"
},
"Lead": {
    "type": "metal",
    "group": "14",
    "period": "6",
    "state": "solid",
    "atomic_number": "82",
    "electron_config": "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²",
    "charge": "+2, +4",
    "metallic": "metal",
    "melting_point": "327",
    "density": "11.34",
    "valence_electrons": "18",
    "radioactive": "no"
},
"Bismuth": {
    "type": "metal",
    "group": "15",
    "period": "6",
    "state": "solid",
    "atomic_number": "83",
    "electron_config": "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³",
    "charge": "+3, +5",
    "metallic": "metal",
    "melting_point": "271",
    "density": "9.78",
    "valence_electrons": "18",
    "radioactive": "no"
},
"Polonium": {
    "type": "metal",
    "group": "16",
    "period": "6",
    "state": "solid",
    "atomic_number": "84",
    "electron_config": "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴",
    "charge": "+2, +4, +6",
    "metallic": "metal",
    "melting_point": "254",
    "density": "9.196",
    "valence_electrons": "18",
    "radioactive": "yes"
},
"Astatine": {
    "type": "non-metal",
    "group": "17",
    "period": "6",
    "state": "solid",
    "atomic_number": "85",
    "electron_config": "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵",
    "charge": "-1",
    "metallic": "non-metal",
    "melting_point": "302",
    "density": "7",
    "valence_electrons": "18",
    "radioactive": "yes"
},
"Radon": {
    "type": "noble gas",
    "group": "18",
    "period": "6",
    "state": "gas",
    "atomic_number": "86",
    "electron_config": "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶",
    "charge": "0",
    "metallic": "non-metal",
    "melting_point": "-71",
    "density": "0.00973",
    "valence_electrons": "18",
    "radioactive": "yes"
},
"Francium": {
    "type": "alkali metal",
    "group": "1",
    "period": "7",
    "state": "solid",
    "atomic_number": "87",
    "electron_config": "[Rn] 7s¹",
    "charge": "+1",
    "metallic": "metal",
    "melting_point": "27",
    "density": "1.87",
    "valence_electrons": "1",
    "radioactive": "yes"
},
"Radium": {
    "type": "alkaline earth metal",
    "group": "2",
    "period": "7",
    "state": "solid",
    "atomic_number": "88",
    "electron_config": "[Rn] 7s²",
    "charge": "+2",
    "metallic": "metal",
    "melting_point": "700",
    "density": "5.5",
    "valence_electrons": "2",
    "radioactive": "yes"
},
"Actinium": {
    "type": "metal",
    "group": "",
    "period": "7",
    "state": "solid",
    "atomic_number": "89",
    "electron_config": "[Rn] 6d¹ 7s²",
    "charge": "+3",
    "metallic": "metal",
    "melting_point": "1050",
    "density": "10.07",
    "valence_electrons": "3",
    "radioactive": "yes"
},
"Thorium": {
    "type": "metal",
    "group": "",
    "period": "7",
    "state": "solid",
    "atomic_number": "90",
    "electron_config": "[Rn] 6d² 7s²",
    "charge": "+4",
    "metallic": "metal",
    "melting_point": "1750",
    "density": "11.72",
    "valence_electrons": "4",
    "radioactive": "yes"
},
"Protactinium": {
    "type": "metal",
    "group": "",
    "period": "7",
    "state": "solid",
    "atomic_number": "91",
    "electron_config": "[Rn] 5f² 6d¹ 7s²",
    "charge": "+5",
    "metallic": "metal",
    "melting_point": "1568",
    "density": "15.37",
    "valence_electrons": "5",
    "radioactive": "yes"
},
"Uranium": {
    "type": "metal",
    "group": "",
    "period": "7",
    "state": "solid",
    "atomic_number": "92",
    "electron_config": "[Rn] 5f³ 6d¹ 7s²",
    "charge": "+3, +4, +5, +6",
    "metallic": "metal",
    "melting_point": "1408",
    "density": "18.95",
    "valence_electrons": "6",
    "radioactive": "yes"
},
"Neptunium": {
    "type": "metal",
    "group": "",
    "period": "7",
    "state": "solid",
    "atomic_number": "93",
    "electron_config": "[Rn] 5f⁴ 6d¹ 7s²",
    "charge": "+3, +4, +5, +6, +7",
    "metallic": "metal",
    "melting_point": "917",
    "density": "20.45",
    "valence_electrons": "7",
    "radioactive": "yes"
},
"Plutonium": {
    "type": "metal",
    "group": "",
    "period": "7",
    "state": "solid",
    "atomic_number": "94",
    "electron_config": "[Rn] 5f⁶ 7s²",
    "charge": "+3, +4, +5, +6, +7",
    "metallic": "metal",
    "melting_point": "913",
    "density": "19.86",
    "valence_electrons": "8",
    "radioactive": "yes"
},
"Americium": {
    "type": "metal",
    "group": "",
    "period": "7",
    "state": "solid",
    "atomic_number": "95",
    "electron_config": "[Rn] 5f⁷ 7s²",
    "charge": "+3, +4, +5, +6",
    "metallic": "metal",
    "melting_point": "1449",
    "density": "13.69",
    "valence_electrons": "9",
    "radioactive": "yes"
},
"Curium": {
    "type": "metal",
    "group": "",
    "period": "7",
    "state": "solid",
    "atomic_number": "96",
    "electron_config": "[Rn] 5f⁷ 6d¹ 7s²",
    "charge": "+3, +4",
    "metallic": "metal",
    "melting_point": "1613",
    "density": "13.51",
    "valence_electrons": "10",
    "radioactive": "yes"
},
"Berkelium": {
    "type": "metal",
    "group": "",
    "period": "7",
    "state": "solid",
    "atomic_number": "97",
    "electron_config": "[Rn] 5f⁹ 7s²",
    "charge": "+3, +4",
    "metallic": "metal",
    "melting_point": "1259",
    "density": "14.78",
    "valence_electrons": "11",
    "radioactive": "yes"
},
"Californium": {
    "type": "metal",
    "group": "",
    "period": "7",
    "state": "solid",
    "atomic_number": "98",
    "electron_config": "[Rn] 5f¹⁰ 7s²",
    "charge": "+3",
    "metallic": "metal",
    "melting_point": "1173",
    "density": "15.1",
    "valence_electrons": "12",
    "radioactive": "yes"
},
"Einsteinium": {
    "type": "metal",
    "group": "",
    "period": "7",
    "state": "solid",
    "atomic_number": "99",
    "electron_config": "[Rn] 5f¹¹ 7s²",
    "charge": "+3",
    "metallic": "metal",
    "melting_point": "1133",
    "density": "8.84",
    "valence_electrons": "13",
    "radioactive": "yes"
},
"Fermium": {
    "type": "metal",
    "group": "",
    "period": "7",
    "state": "solid",
    "atomic_number": "100",
    "electron_config": "[Rn] 5f¹² 7s²",
    "charge": "+3",
    "metallic": "metal",
    "melting_point": "1800",
    "density": "9.7",
    "valence_electrons": "14",
    "radioactive": "yes"
},
"Mendelevium": {
    "type": "metal",
    "group": "",
    "period": "7",
    "state": "solid",
    "atomic_number": "101",
    "electron_config": "[Rn] 5f¹³ 7s²",
    "charge": "+3",
    "metallic": "metal",
    "melting_point": "1100",
    "density": "10.3",
    "valence_electrons": "15",},
"Nobelium": {
    "type": "metal",
    "group": "",
    "period": "7",
    "state": "solid",
    "atomic_number": "102",
    "electron_config": "[Rn] 5f¹⁴ 7s²",
    "charge": "+2, +3",
    "metallic": "metal",
    "melting_point": "1100",
    "density": "9.9",
    "valence_electrons": "16",
    "radioactive": "yes"
},
"Lawrencium": {
    "type": "metal",
    "group": "",
    "period": "7",
    "state": "solid",
    "atomic_number": "103",
    "electron_config": "[Rn] 5f¹⁴ 6d¹ 7s²",
    "charge": "+3",
    "metallic": "metal",
    "melting_point": "1900",
    "density": "15.6",
    "valence_electrons": "17",
    "radioactive": "yes"
},
"Rutherfordium": {
    "type": "transition metal",
    "group": "4",
    "period": "7",
    "state": "solid",
    "atomic_number": "104",
    "electron_config": "[Rn] 5f¹⁴ 6d² 7s²",
    "charge": "+4",
    "metallic": "metal",
    "melting_point": "",
    "density": "",
    "valence_electrons": "18",
    "radioactive": "yes"
},
"Dubnium": {
    "type": "transition metal",
    "group": "5",
    "period": "7",
    "state": "solid",
    "atomic_number": "105",
    "electron_config": "[Rn] 5f¹⁴ 6d³ 7s²",
    "charge": "+5",
    "metallic": "metal",
    "melting_point": "",
    "density": "",
    "valence_electrons": "18",
    "radioactive": "yes"
},
"Seaborgium": {
    "type": "transition metal",
    "group": "6",
    "period": "7",
    "state": "solid",
    "atomic_number": "106",
    "electron_config": "[Rn] 5f¹⁴ 6d⁴ 7s²",
    "charge": "+6",
    "metallic": "metal",
    "melting_point": "",
    "density": "",
    "valence_electrons": "18",
    "radioactive": "yes"
},
"Bohrium": {
    "type": "transition metal",
    "group": "7",
    "period": "7",
    "state": "solid",
    "atomic_number": "107",
    "electron_config": "[Rn] 5f¹⁴ 6d⁵ 7s²",
    "charge": "+7",
    "metallic": "metal",
    "melting_point": "",
    "density": "",
    "valence_electrons": "18",
    "radioactive": "yes"
},
"Hassium": {
    "type": "transition metal",
    "group": "8",
    "period": "7",
    "state": "solid",
    "atomic_number": "108",
    "electron_config": "[Rn] 5f¹⁴ 6d⁶ 7s²",
    "charge": "+8",
    "metallic": "metal",
    "melting_point": "",
    "density": "",
    "valence_electrons": "18",
    "radioactive": "yes"
},
"Meitnerium": {
    "type": "transition metal",
    "group": "9",
    "period": "7",
    "state": "solid",
    "atomic_number": "109",
    "electron_config": "[Rn] 5f¹⁴ 6d⁷ 7s²",
    "charge": "+9",
    "metallic": "metal",
    "melting_point": "",
    "density": "",
    "valence_electrons": "18",
    "radioactive": "yes"
},
"Darmstadtium": {
    "type": "transition metal",
    "group": "10",
    "period": "7",
    "state": "solid",
    "atomic_number": "110",
    "electron_config": "[Rn] 5f¹⁴ 6d⁸ 7s²",
    "charge": "+10",
    "metallic": "metal",
    "melting_point": "",
    "density": "",
    "valence_electrons": "18",
    "radioactive": "yes"
},
"Roentgenium": {
    "type": "transition metal",
    "group": "11",
    "period": "7",
    "state": "solid",
    "atomic_number": "111",
    "electron_config": "[Rn] 5f¹⁴ 6d⁹ 7s²",
    "charge": "+11",
    "metallic": "metal",
    "melting_point": "",
    "density": "",
    "valence_electrons": "18",
    "radioactive": "yes"
},
"Copernicium": {
    "type": "transition metal",
    "group": "12",
    "period": "7",
    "state": "solid",
    "atomic_number": "112",
    "electron_config": "[Rn] 5f¹⁴ 6d¹⁰ 7s²",
    "charge": "+12",
    "metallic": "metal",
    "melting_point": "",
    "density": "",
    "valence_electrons": "18",
    "radioactive": "yes"
},
"Nihonium": {
    "type": "post-transition metal",
    "group": "13",
    "period": "7",
    "state": "solid",
    "atomic_number": "113",
    "electron_config": "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹",
    "charge": "+1",
    "metallic": "metal",
    "melting_point": "",
    "density": "",
    "valence_electrons": "18",
    "radioactive": "yes"
},
"Flerovium": {
    "type": "post-transition metal",
    "group": "14",
    "period": "7",
    "state": "solid",
    "atomic_number": "114",
    "electron_config": "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²",
    "charge": "+2",
    "metallic": "metal",
    "melting_point": "",
    "density": "",
    "valence_electrons": "18",
    "radioactive": "yes"
},
"Moscovium": {
    "type": "post-transition metal",
    "group": "15",
    "period": "7",
    "state": "solid",
    "atomic_number": "115",
    "electron_config": "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³",
    "charge": "+3",
    "metallic": "metal",
    "melting_point": "",
    "density": "",
    "valence_electrons": "18",
    "radioactive": "yes"
},
"Livermorium": {
    "type": "post-transition metal",
    "group": "16",
    "period": "7",
    "state": "solid",
    "atomic_number": "116",
    "electron_config": "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴",
    "charge": "+4",
    "metallic": "metal",
    "melting_point": "",
    "density": "",
    "valence_electrons": "18",
    "radioactive": "yes"
},
"Tennessine": {
    "type": "halogen",
    "group": "17",
    "period": "7",
    "state": "solid",
    "atomic_number": "117",
    "electron_config": "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵",
    "charge": "-1",
    "metallic": "non-metal",
    "melting_point": "",
    "density": "",
    "valence_electrons": "18",
    "radioactive": "yes"
},
"Oganesson": {
    "type": "noble gas",
    "group": "18",
    "period": "7",
    "state": "solid",
    "atomic_number": "118",
    "electron_config": "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶",
    "charge": "0",
    "metallic": "non-metal",
    "melting_point": "",
    "density": "",
    "valence_electrons": "18",
    "radioactive": "yes"
}

        }
    def ask_question(self, question, choices):
        print(question)
        for index, choice in enumerate(choices):
            print(f"{index + 1}. {choice}")
        answer = input("Your choice (enter the number): ")
        return choices[int(answer) - 1]

    def guess_element(self):
        print("Welcome to ElementAkinator! Think of an element, and I'll try to guess it.")
        current_elements = list(self.elements.keys())

        # Question 1: Metal, Non-metal, or Metalloid
        type_question = "Is the element a metal, non-metal, or metalloid?"
        type_choices = ["Metal", "Non-metal", "Metalloid"]
        type_answer = self.ask_question(type_question, type_choices)

        # Narrow down the elements based on type
        current_elements = [element for element in current_elements if self.elements[element]["type"].lower() == type_answer.lower()]

        # Question 2: Group (1-18)
        group_question = "What is the group of the element? (1-18)"
        group_answer = self.ask_question(group_question, [str(i) for i in range(1, 19)])

        # Narrow down the elements based on group
        current_elements = [element for element in current_elements if self.elements[element]["group"] == group_answer]

        # Question 3: State (Gas, Liquid, Solid)
        state_question = "Is the element a gas, liquid, or solid at room temperature?"
        state_choices = ["Gas", "Liquid", "Solid"]
        state_answer = self.ask_question(state_question, state_choices)

        # Narrow down the elements based on state
        current_elements = [element for element in current_elements if self.elements[element]["state"].lower() == state_answer.lower()]

        # Question 4: Period (1-7)
        period_question = "What is the period of the element? (1-7)"
        period_answer = self.ask_question(period_question, [str(i) for i in range(1, 8)])

        # Narrow down the elements based on period
        current_elements = [element for element in current_elements if self.elements[element]["period"] == period_answer]

        # Question 7: Charge
        charge_question = "What is the charge of the element?"
        charge_answer = input(charge_question)
        current_elements = [element for element in current_elements if self.elements[element]["charge"] == charge_answer]
        
        # Question 8:Solid, Liquid, Gas
        state_question = What state is the state of the element?
        state_answer = input(state_question)
        current_element = [element for element in current_element if self.element[element]["state"] == state_answer]

        # Question 9: Radioactivity
        radioactive_question = "Is your element radioactive?
        state_answer = input(radioactive_question)
        current_element = [element for element in current_element if self.element[element]["radioactive"] == radioactive_answer

        # Question 10: What is the density?
        debsity

        # Continue with more questions...

        # Once all questions are asked, make a guess
        if len(current_elements) == 1:
            print(f"I think you're thinking of {current_elements[0]}!")
        else:
            print("Sorry, I couldn't guess the element.")

if __name__ == "__main__":
    akinator = ElementAkinator()
    akinator.guess_element()